$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1511139788437.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0fae567c2b0d4c84aa42593d57a97adb",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5c1e0c307d8a4ac09601cf836353d2ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":0},
            "size":{
              "width":857,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8486dd11d9a74355805932e6b603d663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":0},
                "size":{
                  "width":857,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "5c1e0c307d8a4ac09601cf836353d2ae":{
      "scriptId":"u0"},
    "8486dd11d9a74355805932e6b603d663":{
      "scriptId":"u1"}}});