$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1511139788398.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"faff1c0c8bb74e99a92fcf9b89cb975b",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"546155111ccc495f967e98160e7a64cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":9},
            "size":{
              "width":1081,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b41eceeb1464f28ba6c96960fa1670e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":9},
                "size":{
                  "width":1081,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.jpg"}},
{
          "id":"9e6ddcc51fdb4a1eae318c3667dc178b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":60},
            "size":{
              "width":1081,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a755225214f49a2817d8e5944cd816f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":60},
                "size":{
                  "width":1081,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"f9fed721ab004fa5ba5a862b972d35b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":221},
            "size":{
              "width":1091,
              "height":509}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"003a61a5b7db4f268904a0d303f111bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":221},
                "size":{
                  "width":1091,
                  "height":509}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.jpg"}},
{
          "id":"59c7ed7c6fd1483c8b4b563214e0e00a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":768},
            "size":{
              "width":1091,
              "height":390}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6a8fcd6901d43bcb77f438880a6fc7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":768},
                "size":{
                  "width":1091,
                  "height":390}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u6.jpg"}},
{
          "id":"f68626128b2e4f87857a7b3df82bad5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1183},
            "size":{
              "width":1040,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c29d6ba17c47e9a428d6d31220d961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1183},
                "size":{
                  "width":1040,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.jpg"}},
{
          "id":"e09c3f72dc5a4709a730dcae6762efa4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1654},
            "size":{
              "width":1040,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd86442c3734f2c962343183721aaa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":1654},
                "size":{
                  "width":1040,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u8.jpg"}},
{
          "id":"fcb3a158da1942f78acb6f7a97fdace1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":2094},
            "size":{
              "width":766,
              "height":184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f31701f5d5342259ae92abf5abcefa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":2094},
                "size":{
                  "width":766,
                  "height":184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e27834f5e2bc4bb1b78874f2954ab20c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":2323},
            "size":{
              "width":1026,
              "height":414}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82b21f70ba1b45f293838f8bad7cb537",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":2323},
                "size":{
                  "width":1026,
                  "height":414}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "546155111ccc495f967e98160e7a64cb":{
      "scriptId":"u0"},
    "6b41eceeb1464f28ba6c96960fa1670e":{
      "scriptId":"u1"},
    "9e6ddcc51fdb4a1eae318c3667dc178b":{
      "scriptId":"u2"},
    "7a755225214f49a2817d8e5944cd816f":{
      "scriptId":"u3"},
    "f9fed721ab004fa5ba5a862b972d35b0":{
      "scriptId":"u4"},
    "003a61a5b7db4f268904a0d303f111bd":{
      "scriptId":"u5"},
    "59c7ed7c6fd1483c8b4b563214e0e00a":{
      "scriptId":"u6"},
    "f6a8fcd6901d43bcb77f438880a6fc7f":{
      "scriptId":"u7"},
    "f68626128b2e4f87857a7b3df82bad5a":{
      "scriptId":"u8"},
    "f5c29d6ba17c47e9a428d6d31220d961":{
      "scriptId":"u9"},
    "e09c3f72dc5a4709a730dcae6762efa4":{
      "scriptId":"u10"},
    "8fd86442c3734f2c962343183721aaa4":{
      "scriptId":"u11"},
    "fcb3a158da1942f78acb6f7a97fdace1":{
      "scriptId":"u12"},
    "9f31701f5d5342259ae92abf5abcefa7":{
      "scriptId":"u13"},
    "e27834f5e2bc4bb1b78874f2954ab20c":{
      "scriptId":"u14"},
    "82b21f70ba1b45f293838f8bad7cb537":{
      "scriptId":"u15"}}});