$axure.loadCurrentPage({
  "url":"付款页.html",
  "generationDate":new Date(1511139788793.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c74481d0ea1f465f87629c92f241de8b",
    "type":"Axure:Page",
    "name":"付款页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"30ebbc11d53c4abca3d63972484c204c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":1490,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263fdf2c1a3b4442afeda360e7f67343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":1490,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付款页/u0.png"}},
{
          "id":"b5e31b82d4e04ce4b5470b233eaf0975",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":1510,
              "height":780}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4610e6623db14fbe8e150e821999fcb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":1510,
                  "height":780}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付款页/u2.png"}},
{
          "id":"8cb3b6b6b92d4657ae719d4e15cd773e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":921},
            "size":{
              "width":1430,
              "height":204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4af62dcd69654ae3ad0574d87e326454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":921},
                "size":{
                  "width":1430,
                  "height":204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付款页/u4.png"}},
{
          "id":"246a9b1a897b43a4b1a9f7b9b8e72d63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-76,
              "y":0},
            "size":{
              "width":1876,
              "height":1090}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af348893b1394f70a1f7763cdd75f757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-76,
                  "y":0},
                "size":{
                  "width":1876,
                  "height":1090}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/付款页/u6.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "30ebbc11d53c4abca3d63972484c204c":{
      "scriptId":"u0"},
    "263fdf2c1a3b4442afeda360e7f67343":{
      "scriptId":"u1"},
    "b5e31b82d4e04ce4b5470b233eaf0975":{
      "scriptId":"u2"},
    "4610e6623db14fbe8e150e821999fcb7":{
      "scriptId":"u3"},
    "8cb3b6b6b92d4657ae719d4e15cd773e":{
      "scriptId":"u4"},
    "4af62dcd69654ae3ad0574d87e326454":{
      "scriptId":"u5"},
    "246a9b1a897b43a4b1a9f7b9b8e72d63":{
      "scriptId":"u6"},
    "af348893b1394f70a1f7763cdd75f757":{
      "scriptId":"u7"}}});